# Generated by Django 3.0.8 on 2020-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
