# Generated by Django 3.0.8 on 2020-08-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='theme',
            field=models.CharField(default='day', max_length=10),
        ),
    ]
